name: spatial_cost_opt
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pip

  - atlite>=0.2.6
  - earth-osm>=0.1.0, <0.2.0
  - dask

  - xlrd
  - openpyxl
  - pycountry
  - snakemake-minimal
  - memory_profiler
  - pre-commit
  - yaml
  - pytables
  - lxml
  - numpy
  - pandas = 1.4.3

  - geopandas>=0.11.1
  - xarray
  - netcdf4
  - networkx
  - shapely
  - progressbar2
  - matplotlib
  - proj
  - fiona <= 1.18.20  

  # Keep in conda environment when calling ipython
  - ipython
  - ipykernel
  - rasterio
  - tqdm
  - pytz
  - ipykernel
  - pip:
    - vresutils>=0.3.1
    - black
    - cdsapi
    - git+https://github.com/snakemake/snakemake
