name: spatial_cost_opt
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - pip

  # GIS
  - atlite >=0.2.11
  - fiona <= 1.18.20 
  - geopandas >=0.11.1
  - proj
  - rasterio =>1.2.10
  - richdem
  - shapely
  # - earth-osm>=0.1.0, <0.2.0
# https://pyrosm.readthedocs.io/en/latest/installation.html
  # Network optimisation
  - pyomo
  - xarray
  - rioxarray
  - networkx

  - dask
  - lxml
  - matplotlib
  - memory_profiler
  - netcdf4
  - numpy
  - pandas >=1.4.3
  - pre-commit
  - progressbar2
  - pycountry
  - pytables
  - openpyxl
  - snakemake-minimal=7.30.1
  - xlrd
  - yaml

  - ipython
  - ipykernel
  - tqdm
  - pytz

  # solvers
  - gurobi
  - ipopt 
  - glpk

  - pip:
    - black
    - cdsapi
    - highspy
    - linopy >=0.2
    - vresutils >=0.3.1
    - snakemake_interface_executor_plugins==1.0.1
    - git+https://github.com/snakemake/snakemake.git
